#!/usr/bin/env python3
"""Generate c/include/methods_generated.h from shared/methods.json.

This is the C-side method registry. It is regenerated by the CMake build (see
langs/c/CMakeLists.txt) whenever shared/methods.json changes. Do not edit the generated
header by hand.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "shared" / "methods.json"
OUT = ROOT / "langs" / "c" / "include" / "methods_generated.h"

OFFSET_KEYS = ["Imsak", "Fajr", "Sunrise", "Dhuhr", "Asr", "Maghrib", "Sunset", "Isha", "Midnight"]


def num(x):
    m = re.match(r"[0-9.+\-]+", str(x))
    return float(m.group(0)) if m else 0.0


def is_min(x):
    return "min" in str(x)


def c_str(s):
    if s is None:
        return "NULL"
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def fmt_double(v):
    return repr(float(v))


def tune_array(tune):
    arr = [0.0] * 9
    if tune:
        for key, val in tune.items():
            if key in OFFSET_KEYS:
                arr[OFFSET_KEYS.index(key)] = float(val)
    return "{" + ",".join(fmt_double(v) for v in arr) + "}"


def flatten(methods):
    """Expand `extends` into fully-resolved `params` (base first, child overrides)."""

    def base_params(key, stack):
        entry = methods[key]
        base = entry.get("extends")
        params = {}
        if base:
            if base not in methods:
                raise ValueError(f"unknown 'extends': {base} (in {key})")
            if base in stack:
                raise ValueError("'extends' cycle: " + " -> ".join(stack + [base]))
            params = base_params(base, stack + [key])
        params.update(entry.get("params", {}))
        return params

    out = {}
    for key, entry in methods.items():
        e = dict(entry)
        if "extends" in e:
            e.pop("extends")
            e["params"] = base_params(key, [key])
        out[key] = e
    return out


def main():
    methods = json.loads(SRC.read_text())
    methods = flatten(methods)
    entries = [(key, methods[key]) for key in methods]
    entries.sort(key=lambda kv: kv[1]["id"])

    lines = []
    lines.append("/* Auto-generated from shared/methods.json by scripts/generate_c_methods.py.")
    lines.append(" * Do not edit by hand. */")
    lines.append("#ifndef METHODS_GENERATED_H")
    lines.append("#define METHODS_GENERATED_H")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    int id;")
    lines.append("    const char *key;")
    lines.append("    const char *name;")
    lines.append("    double fajr;")
    lines.append("    double isha;")
    lines.append("    int isha_is_minutes;")
    lines.append("    double maghrib;")
    lines.append("    int maghrib_is_minutes;")
    lines.append("    double imsak;")
    lines.append("    double dhuhr;")
    lines.append("    int midnight_jafari;")
    lines.append("    const char *shafaq;")
    lines.append("    double default_tune[9];")
    lines.append("    double ramadan_tune[9];")
    lines.append("} pt_method;")
    lines.append("")
    lines.append(f"#define PT_METHOD_COUNT {len(entries)}")
    lines.append("")
    lines.append("static const pt_method pt_methods[PT_METHOD_COUNT] = {")
    for key, e in entries:
        p = e.get("params", {})
        fajr = num(p.get("Fajr", 0))
        isha_raw = p.get("Isha", 0)
        maghrib_raw = p.get("Maghrib", "0 min")
        imsak = num(p.get("Imsak", "10 min"))
        dhuhr = num(p.get("Dhuhr", "0 min"))
        midnight_jafari = 1 if p.get("Midnight") == "JAFARI" else 0
        shafaq = p.get("shafaq")
        default_tune = tune_array(e.get("defaultTune"))
        ramadan_tune = tune_array(e.get("ramadanTune"))
        fields = [
            str(e["id"]),
            c_str(key),
            c_str(e.get("name", "")),
            fmt_double(fajr),
            fmt_double(num(isha_raw)),
            "1" if is_min(isha_raw) else "0",
            fmt_double(num(maghrib_raw)),
            "1" if is_min(maghrib_raw) else "0",
            fmt_double(imsak),
            fmt_double(dhuhr),
            str(midnight_jafari),
            c_str(shafaq),
            default_tune,
            ramadan_tune,
        ]
        lines.append("    { " + ", ".join(fields) + " },")
    lines.append("};")
    lines.append("")
    lines.append("#endif")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"generated {OUT.relative_to(ROOT)} ({len(entries)} methods)")


if __name__ == "__main__":
    main()
