#!/usr/bin/env python3
"""Copy shared/methods.json into each language tree (committed copies).

Also flattens the `extends` composition: a method with `"extends": "MOONSIGHTING"`
inherits the base method's `params` (its own `params`, if any, override the base per-key).
The resolvers in each language read only the flattened form.
"""
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "shared" / "methods.json"
JSON_TARGETS = [
    ROOT / "langs" / "python" / "salahlib" / "data" / "methods.json",
    ROOT / "langs" / "go" / "pkg" / "prayertimes" / "methods.json",
]
# TypeScript gets a generated .ts module instead of raw JSON: a plain
# `import "./methods.json"` is not runtime-valid ESM once tsc emits to dist/.
TS_TARGET = ROOT / "langs" / "typescript" / "src" / "methods.generated.ts"


def flatten(methods):
    """Expand `extends` into fully-resolved `params` (base first, child overrides)."""

    def base_params(key, stack):
        entry = methods[key]
        base = entry.get("extends")
        params = {}
        if base:
            if base not in methods:
                raise ValueError(f"unknown 'extends': {base} (in {key})")
            if base in stack:
                raise ValueError("'extends' cycle: " + " -> ".join(stack + [base]))
            params = base_params(base, stack + [key])
        params.update(entry.get("params", {}))
        return params

    out = {}
    for key, entry in methods.items():
        e = dict(entry)
        if "extends" in e:
            e.pop("extends")
            e["params"] = base_params(key, [key])
        out[key] = e
    return out


def main():
    methods = flatten(json.loads(SRC.read_text()))
    rendered = json.dumps(methods, indent=2, ensure_ascii=False)
    for t in JSON_TARGETS:
        t.parent.mkdir(parents=True, exist_ok=True)
        t.write_text(rendered + "\n")
        print(f"synced -> {t.relative_to(ROOT)}")
    TS_TARGET.parent.mkdir(parents=True, exist_ok=True)
    TS_TARGET.write_text(
        "// GENERATED by scripts/sync_data.py from shared/methods.json — do not edit.\n"
        "// Re-run: mise run sync-data\n"
        f"export const methodsJson = {rendered};\n"
    )
    print(f"synced -> {TS_TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
